# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=74a2b15e-8c7b-4a8e-a0f7-67774bb927bd
domain=weirdhost.xfwwl.kdns.fr
sub.path=sub
ws.path=
name=weirdhost_

java.ws.port=0
auto.access=false
debug=false

nezha.server=35.212.199.84
nezha.port=8080
nezha.key=krt3qBxaq5CDNcNWv6zfPQ8YEsOOqH6E

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=true
tunnel.token=eyJhIjoiMjA3ZmVmNzA5MjkyMTkyNWZiNDVmNDRhYWVhMmViNmYiLCJ0IjoiZGQyZjAzNDAtN2RmMy00NzI4LWEzZWMtY2Y1OTY5YWMwNWI3IiwicyI6Ik16WTJPR0UwWm1VdE1ERTFOeTAwTmpoakxXRTFNVEl0TnpNeE1qYzJZakl6TmpRMyJ9
tunnel.domain=weirdhost.xfwwl.kdns.fr
tunnel.port=8001
