# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=63487cd5-ac9c-425e-8450-eee18a759d76

domain=
sub.path=sub
ws.path=
name=

java.ws.port=0
auto.access=false
debug=false

nezha.server=
nezha.port=
nezha.key=

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=true
tunnel.token=
tunnel.domain=
tunnel.port=8001
