# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=93908a6c-bec7-4e1c-a70b-16dede1e25e8
domain=freezehost.xfwwl.dpdns.org
sub.path=sub
ws.path=
name=freezehost_

java.ws.port=0
auto.access=false
debug=false

nezha.server=35.212.199.84
nezha.port=8080
nezha.key=krt3qBxaq5CDNcNWv6zfPQ8YEsOOqH6E

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=true
tunnel.token=eyJhIjoiMjA3ZmVmNzA5MjkyMTkyNWZiNDVmNDRhYWVhMmViNmYiLCJ0IjoiMDlhODYyNDEtZGE4Zi00ZTVkLTkwY2EtZTNjMmRkOGU0MmE3IiwicyI6Ik56ZzJNRE16T1RndE1tSTBNUzAwTmpFMkxUa3dNVFV0TUROak9UQmlNalJpWTJNMyJ9
tunnel.domain=freezehost.xfwwl.dpdns.org
tunnel.port=8001
