// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface GeoIPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GeoIP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool use6 = 1;</code>
   * @return The use6.
   */
  boolean getUse6();

  /**
   * <code>.proto.IP ip = 2;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>.proto.IP ip = 2;</code>
   * @return The ip.
   */
  com.nezhahq.agent.proto.IP getIp();
  /**
   * <code>.proto.IP ip = 2;</code>
   */
  com.nezhahq.agent.proto.IPOrBuilder getIpOrBuilder();

  /**
   * <code>string country_code = 3;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 3;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>uint64 dashboard_boot_time = 4;</code>
   * @return The dashboardBootTime.
   */
  long getDashboardBootTime();
}
