// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

/**
 * Protobuf type {@code proto.GeoIP}
 */
public final class GeoIP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GeoIP)
    GeoIPOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoIP.newBuilder() to construct.
  private GeoIP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoIP() {
    countryCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoIP();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_GeoIP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_GeoIP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nezhahq.agent.proto.GeoIP.class, com.nezhahq.agent.proto.GeoIP.Builder.class);
  }

  private int bitField0_;
  public static final int USE6_FIELD_NUMBER = 1;
  private boolean use6_ = false;
  /**
   * <code>bool use6 = 1;</code>
   * @return The use6.
   */
  @java.lang.Override
  public boolean getUse6() {
    return use6_;
  }

  public static final int IP_FIELD_NUMBER = 2;
  private com.nezhahq.agent.proto.IP ip_;
  /**
   * <code>.proto.IP ip = 2;</code>
   * @return Whether the ip field is set.
   */
  @java.lang.Override
  public boolean hasIp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.IP ip = 2;</code>
   * @return The ip.
   */
  @java.lang.Override
  public com.nezhahq.agent.proto.IP getIp() {
    return ip_ == null ? com.nezhahq.agent.proto.IP.getDefaultInstance() : ip_;
  }
  /**
   * <code>.proto.IP ip = 2;</code>
   */
  @java.lang.Override
  public com.nezhahq.agent.proto.IPOrBuilder getIpOrBuilder() {
    return ip_ == null ? com.nezhahq.agent.proto.IP.getDefaultInstance() : ip_;
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object countryCode_ = "";
  /**
   * <code>string country_code = 3;</code>
   * @return The countryCode.
   */
  @java.lang.Override
  public java.lang.String getCountryCode() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 3;</code>
   * @return The bytes for countryCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DASHBOARD_BOOT_TIME_FIELD_NUMBER = 4;
  private long dashboardBootTime_ = 0L;
  /**
   * <code>uint64 dashboard_boot_time = 4;</code>
   * @return The dashboardBootTime.
   */
  @java.lang.Override
  public long getDashboardBootTime() {
    return dashboardBootTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (use6_ != false) {
      output.writeBool(1, use6_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getIp());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryCode_);
    }
    if (dashboardBootTime_ != 0L) {
      output.writeUInt64(4, dashboardBootTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (use6_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, use6_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getIp());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryCode_);
    }
    if (dashboardBootTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, dashboardBootTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nezhahq.agent.proto.GeoIP)) {
      return super.equals(obj);
    }
    com.nezhahq.agent.proto.GeoIP other = (com.nezhahq.agent.proto.GeoIP) obj;

    if (getUse6()
        != other.getUse6()) return false;
    if (hasIp() != other.hasIp()) return false;
    if (hasIp()) {
      if (!getIp()
          .equals(other.getIp())) return false;
    }
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (getDashboardBootTime()
        != other.getDashboardBootTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USE6_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUse6());
    if (hasIp()) {
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
    }
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + DASHBOARD_BOOT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDashboardBootTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nezhahq.agent.proto.GeoIP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nezhahq.agent.proto.GeoIP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.GeoIP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nezhahq.agent.proto.GeoIP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GeoIP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GeoIP)
      com.nezhahq.agent.proto.GeoIPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_GeoIP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_GeoIP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nezhahq.agent.proto.GeoIP.class, com.nezhahq.agent.proto.GeoIP.Builder.class);
    }

    // Construct using com.nezhahq.agent.proto.GeoIP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIpFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      use6_ = false;
      ip_ = null;
      if (ipBuilder_ != null) {
        ipBuilder_.dispose();
        ipBuilder_ = null;
      }
      countryCode_ = "";
      dashboardBootTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_GeoIP_descriptor;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.GeoIP getDefaultInstanceForType() {
      return com.nezhahq.agent.proto.GeoIP.getDefaultInstance();
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.GeoIP build() {
      com.nezhahq.agent.proto.GeoIP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.GeoIP buildPartial() {
      com.nezhahq.agent.proto.GeoIP result = new com.nezhahq.agent.proto.GeoIP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nezhahq.agent.proto.GeoIP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.use6_ = use6_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ip_ = ipBuilder_ == null
            ? ip_
            : ipBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.countryCode_ = countryCode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dashboardBootTime_ = dashboardBootTime_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nezhahq.agent.proto.GeoIP) {
        return mergeFrom((com.nezhahq.agent.proto.GeoIP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nezhahq.agent.proto.GeoIP other) {
      if (other == com.nezhahq.agent.proto.GeoIP.getDefaultInstance()) return this;
      if (other.getUse6() != false) {
        setUse6(other.getUse6());
      }
      if (other.hasIp()) {
        mergeIp(other.getIp());
      }
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getDashboardBootTime() != 0L) {
        setDashboardBootTime(other.getDashboardBootTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              use6_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getIpFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              countryCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              dashboardBootTime_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean use6_ ;
    /**
     * <code>bool use6 = 1;</code>
     * @return The use6.
     */
    @java.lang.Override
    public boolean getUse6() {
      return use6_;
    }
    /**
     * <code>bool use6 = 1;</code>
     * @param value The use6 to set.
     * @return This builder for chaining.
     */
    public Builder setUse6(boolean value) {

      use6_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool use6 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUse6() {
      bitField0_ = (bitField0_ & ~0x00000001);
      use6_ = false;
      onChanged();
      return this;
    }

    private com.nezhahq.agent.proto.IP ip_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nezhahq.agent.proto.IP, com.nezhahq.agent.proto.IP.Builder, com.nezhahq.agent.proto.IPOrBuilder> ipBuilder_;
    /**
     * <code>.proto.IP ip = 2;</code>
     * @return Whether the ip field is set.
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     * @return The ip.
     */
    public com.nezhahq.agent.proto.IP getIp() {
      if (ipBuilder_ == null) {
        return ip_ == null ? com.nezhahq.agent.proto.IP.getDefaultInstance() : ip_;
      } else {
        return ipBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public Builder setIp(com.nezhahq.agent.proto.IP value) {
      if (ipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ip_ = value;
      } else {
        ipBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public Builder setIp(
        com.nezhahq.agent.proto.IP.Builder builderForValue) {
      if (ipBuilder_ == null) {
        ip_ = builderForValue.build();
      } else {
        ipBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public Builder mergeIp(com.nezhahq.agent.proto.IP value) {
      if (ipBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          ip_ != null &&
          ip_ != com.nezhahq.agent.proto.IP.getDefaultInstance()) {
          getIpBuilder().mergeFrom(value);
        } else {
          ip_ = value;
        }
      } else {
        ipBuilder_.mergeFrom(value);
      }
      if (ip_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public Builder clearIp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ip_ = null;
      if (ipBuilder_ != null) {
        ipBuilder_.dispose();
        ipBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public com.nezhahq.agent.proto.IP.Builder getIpBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getIpFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    public com.nezhahq.agent.proto.IPOrBuilder getIpOrBuilder() {
      if (ipBuilder_ != null) {
        return ipBuilder_.getMessageOrBuilder();
      } else {
        return ip_ == null ?
            com.nezhahq.agent.proto.IP.getDefaultInstance() : ip_;
      }
    }
    /**
     * <code>.proto.IP ip = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nezhahq.agent.proto.IP, com.nezhahq.agent.proto.IP.Builder, com.nezhahq.agent.proto.IPOrBuilder> 
        getIpFieldBuilder() {
      if (ipBuilder_ == null) {
        ipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nezhahq.agent.proto.IP, com.nezhahq.agent.proto.IP.Builder, com.nezhahq.agent.proto.IPOrBuilder>(
                getIp(),
                getParentForChildren(),
                isClean());
        ip_ = null;
      }
      return ipBuilder_;
    }

    private java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 3;</code>
     * @return The countryCode.
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country_code = 3;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 3;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      countryCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      countryCode_ = getDefaultInstance().getCountryCode();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 3;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      countryCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long dashboardBootTime_ ;
    /**
     * <code>uint64 dashboard_boot_time = 4;</code>
     * @return The dashboardBootTime.
     */
    @java.lang.Override
    public long getDashboardBootTime() {
      return dashboardBootTime_;
    }
    /**
     * <code>uint64 dashboard_boot_time = 4;</code>
     * @param value The dashboardBootTime to set.
     * @return This builder for chaining.
     */
    public Builder setDashboardBootTime(long value) {

      dashboardBootTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 dashboard_boot_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDashboardBootTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      dashboardBootTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GeoIP)
  }

  // @@protoc_insertion_point(class_scope:proto.GeoIP)
  private static final com.nezhahq.agent.proto.GeoIP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nezhahq.agent.proto.GeoIP();
  }

  public static com.nezhahq.agent.proto.GeoIP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoIP>
      PARSER = new com.google.protobuf.AbstractParser<GeoIP>() {
    @java.lang.Override
    public GeoIP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GeoIP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoIP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nezhahq.agent.proto.GeoIP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

