// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface HostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Host)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string platform = 1;</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <code>string platform = 1;</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();

  /**
   * <code>string platform_version = 2;</code>
   * @return The platformVersion.
   */
  java.lang.String getPlatformVersion();
  /**
   * <code>string platform_version = 2;</code>
   * @return The bytes for platformVersion.
   */
  com.google.protobuf.ByteString
      getPlatformVersionBytes();

  /**
   * <code>repeated string cpu = 3;</code>
   * @return A list containing the cpu.
   */
  java.util.List<java.lang.String>
      getCpuList();
  /**
   * <code>repeated string cpu = 3;</code>
   * @return The count of cpu.
   */
  int getCpuCount();
  /**
   * <code>repeated string cpu = 3;</code>
   * @param index The index of the element to return.
   * @return The cpu at the given index.
   */
  java.lang.String getCpu(int index);
  /**
   * <code>repeated string cpu = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cpu at the given index.
   */
  com.google.protobuf.ByteString
      getCpuBytes(int index);

  /**
   * <code>uint64 mem_total = 4;</code>
   * @return The memTotal.
   */
  long getMemTotal();

  /**
   * <code>uint64 disk_total = 5;</code>
   * @return The diskTotal.
   */
  long getDiskTotal();

  /**
   * <code>uint64 swap_total = 6;</code>
   * @return The swapTotal.
   */
  long getSwapTotal();

  /**
   * <code>string arch = 7;</code>
   * @return The arch.
   */
  java.lang.String getArch();
  /**
   * <code>string arch = 7;</code>
   * @return The bytes for arch.
   */
  com.google.protobuf.ByteString
      getArchBytes();

  /**
   * <code>string virtualization = 8;</code>
   * @return The virtualization.
   */
  java.lang.String getVirtualization();
  /**
   * <code>string virtualization = 8;</code>
   * @return The bytes for virtualization.
   */
  com.google.protobuf.ByteString
      getVirtualizationBytes();

  /**
   * <code>uint64 boot_time = 9;</code>
   * @return The bootTime.
   */
  long getBootTime();

  /**
   * <code>string version = 10;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>repeated string gpu = 11;</code>
   * @return A list containing the gpu.
   */
  java.util.List<java.lang.String>
      getGpuList();
  /**
   * <code>repeated string gpu = 11;</code>
   * @return The count of gpu.
   */
  int getGpuCount();
  /**
   * <code>repeated string gpu = 11;</code>
   * @param index The index of the element to return.
   * @return The gpu at the given index.
   */
  java.lang.String getGpu(int index);
  /**
   * <code>repeated string gpu = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the gpu at the given index.
   */
  com.google.protobuf.ByteString
      getGpuBytes(int index);
}
