// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

/**
 * Protobuf type {@code proto.Host}
 */
public final class Host extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Host)
    HostOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Host.newBuilder() to construct.
  private Host(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Host() {
    platform_ = "";
    platformVersion_ = "";
    cpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    arch_ = "";
    virtualization_ = "";
    version_ = "";
    gpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Host();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_Host_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_Host_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nezhahq.agent.proto.Host.class, com.nezhahq.agent.proto.Host.Builder.class);
  }

  public static final int PLATFORM_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object platform_ = "";
  /**
   * <code>string platform = 1;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <code>string platform = 1;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object platformVersion_ = "";
  /**
   * <code>string platform_version = 2;</code>
   * @return The platformVersion.
   */
  @java.lang.Override
  public java.lang.String getPlatformVersion() {
    java.lang.Object ref = platformVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platformVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string platform_version = 2;</code>
   * @return The bytes for platformVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformVersionBytes() {
    java.lang.Object ref = platformVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platformVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList cpu_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string cpu = 3;</code>
   * @return A list containing the cpu.
   */
  public com.google.protobuf.ProtocolStringList
      getCpuList() {
    return cpu_;
  }
  /**
   * <code>repeated string cpu = 3;</code>
   * @return The count of cpu.
   */
  public int getCpuCount() {
    return cpu_.size();
  }
  /**
   * <code>repeated string cpu = 3;</code>
   * @param index The index of the element to return.
   * @return The cpu at the given index.
   */
  public java.lang.String getCpu(int index) {
    return cpu_.get(index);
  }
  /**
   * <code>repeated string cpu = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cpu at the given index.
   */
  public com.google.protobuf.ByteString
      getCpuBytes(int index) {
    return cpu_.getByteString(index);
  }

  public static final int MEM_TOTAL_FIELD_NUMBER = 4;
  private long memTotal_ = 0L;
  /**
   * <code>uint64 mem_total = 4;</code>
   * @return The memTotal.
   */
  @java.lang.Override
  public long getMemTotal() {
    return memTotal_;
  }

  public static final int DISK_TOTAL_FIELD_NUMBER = 5;
  private long diskTotal_ = 0L;
  /**
   * <code>uint64 disk_total = 5;</code>
   * @return The diskTotal.
   */
  @java.lang.Override
  public long getDiskTotal() {
    return diskTotal_;
  }

  public static final int SWAP_TOTAL_FIELD_NUMBER = 6;
  private long swapTotal_ = 0L;
  /**
   * <code>uint64 swap_total = 6;</code>
   * @return The swapTotal.
   */
  @java.lang.Override
  public long getSwapTotal() {
    return swapTotal_;
  }

  public static final int ARCH_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object arch_ = "";
  /**
   * <code>string arch = 7;</code>
   * @return The arch.
   */
  @java.lang.Override
  public java.lang.String getArch() {
    java.lang.Object ref = arch_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arch_ = s;
      return s;
    }
  }
  /**
   * <code>string arch = 7;</code>
   * @return The bytes for arch.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArchBytes() {
    java.lang.Object ref = arch_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arch_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIRTUALIZATION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object virtualization_ = "";
  /**
   * <code>string virtualization = 8;</code>
   * @return The virtualization.
   */
  @java.lang.Override
  public java.lang.String getVirtualization() {
    java.lang.Object ref = virtualization_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      virtualization_ = s;
      return s;
    }
  }
  /**
   * <code>string virtualization = 8;</code>
   * @return The bytes for virtualization.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVirtualizationBytes() {
    java.lang.Object ref = virtualization_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      virtualization_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOT_TIME_FIELD_NUMBER = 9;
  private long bootTime_ = 0L;
  /**
   * <code>uint64 boot_time = 9;</code>
   * @return The bootTime.
   */
  @java.lang.Override
  public long getBootTime() {
    return bootTime_;
  }

  public static final int VERSION_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 10;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GPU_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList gpu_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string gpu = 11;</code>
   * @return A list containing the gpu.
   */
  public com.google.protobuf.ProtocolStringList
      getGpuList() {
    return gpu_;
  }
  /**
   * <code>repeated string gpu = 11;</code>
   * @return The count of gpu.
   */
  public int getGpuCount() {
    return gpu_.size();
  }
  /**
   * <code>repeated string gpu = 11;</code>
   * @param index The index of the element to return.
   * @return The gpu at the given index.
   */
  public java.lang.String getGpu(int index) {
    return gpu_.get(index);
  }
  /**
   * <code>repeated string gpu = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the gpu at the given index.
   */
  public com.google.protobuf.ByteString
      getGpuBytes(int index) {
    return gpu_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platformVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, platformVersion_);
    }
    for (int i = 0; i < cpu_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cpu_.getRaw(i));
    }
    if (memTotal_ != 0L) {
      output.writeUInt64(4, memTotal_);
    }
    if (diskTotal_ != 0L) {
      output.writeUInt64(5, diskTotal_);
    }
    if (swapTotal_ != 0L) {
      output.writeUInt64(6, swapTotal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arch_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, arch_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(virtualization_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, virtualization_);
    }
    if (bootTime_ != 0L) {
      output.writeUInt64(9, bootTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, version_);
    }
    for (int i = 0; i < gpu_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, gpu_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platformVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, platformVersion_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cpu_.size(); i++) {
        dataSize += computeStringSizeNoTag(cpu_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCpuList().size();
    }
    if (memTotal_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, memTotal_);
    }
    if (diskTotal_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, diskTotal_);
    }
    if (swapTotal_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, swapTotal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arch_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, arch_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(virtualization_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, virtualization_);
    }
    if (bootTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, bootTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, version_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < gpu_.size(); i++) {
        dataSize += computeStringSizeNoTag(gpu_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGpuList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nezhahq.agent.proto.Host)) {
      return super.equals(obj);
    }
    com.nezhahq.agent.proto.Host other = (com.nezhahq.agent.proto.Host) obj;

    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (!getPlatformVersion()
        .equals(other.getPlatformVersion())) return false;
    if (!getCpuList()
        .equals(other.getCpuList())) return false;
    if (getMemTotal()
        != other.getMemTotal()) return false;
    if (getDiskTotal()
        != other.getDiskTotal()) return false;
    if (getSwapTotal()
        != other.getSwapTotal()) return false;
    if (!getArch()
        .equals(other.getArch())) return false;
    if (!getVirtualization()
        .equals(other.getVirtualization())) return false;
    if (getBootTime()
        != other.getBootTime()) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getGpuList()
        .equals(other.getGpuList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    hash = (37 * hash) + PLATFORM_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getPlatformVersion().hashCode();
    if (getCpuCount() > 0) {
      hash = (37 * hash) + CPU_FIELD_NUMBER;
      hash = (53 * hash) + getCpuList().hashCode();
    }
    hash = (37 * hash) + MEM_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemTotal());
    hash = (37 * hash) + DISK_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDiskTotal());
    hash = (37 * hash) + SWAP_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSwapTotal());
    hash = (37 * hash) + ARCH_FIELD_NUMBER;
    hash = (53 * hash) + getArch().hashCode();
    hash = (37 * hash) + VIRTUALIZATION_FIELD_NUMBER;
    hash = (53 * hash) + getVirtualization().hashCode();
    hash = (37 * hash) + BOOT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBootTime());
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (getGpuCount() > 0) {
      hash = (37 * hash) + GPU_FIELD_NUMBER;
      hash = (53 * hash) + getGpuList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nezhahq.agent.proto.Host parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nezhahq.agent.proto.Host parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nezhahq.agent.proto.Host parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.Host parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nezhahq.agent.proto.Host prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Host}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Host)
      com.nezhahq.agent.proto.HostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_Host_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_Host_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nezhahq.agent.proto.Host.class, com.nezhahq.agent.proto.Host.Builder.class);
    }

    // Construct using com.nezhahq.agent.proto.Host.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      platform_ = "";
      platformVersion_ = "";
      cpu_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      memTotal_ = 0L;
      diskTotal_ = 0L;
      swapTotal_ = 0L;
      arch_ = "";
      virtualization_ = "";
      bootTime_ = 0L;
      version_ = "";
      gpu_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_Host_descriptor;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.Host getDefaultInstanceForType() {
      return com.nezhahq.agent.proto.Host.getDefaultInstance();
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.Host build() {
      com.nezhahq.agent.proto.Host result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.Host buildPartial() {
      com.nezhahq.agent.proto.Host result = new com.nezhahq.agent.proto.Host(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nezhahq.agent.proto.Host result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.platform_ = platform_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.platformVersion_ = platformVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        cpu_.makeImmutable();
        result.cpu_ = cpu_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.memTotal_ = memTotal_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.diskTotal_ = diskTotal_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.swapTotal_ = swapTotal_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.arch_ = arch_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.virtualization_ = virtualization_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.bootTime_ = bootTime_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        gpu_.makeImmutable();
        result.gpu_ = gpu_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nezhahq.agent.proto.Host) {
        return mergeFrom((com.nezhahq.agent.proto.Host)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nezhahq.agent.proto.Host other) {
      if (other == com.nezhahq.agent.proto.Host.getDefaultInstance()) return this;
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPlatformVersion().isEmpty()) {
        platformVersion_ = other.platformVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.cpu_.isEmpty()) {
        if (cpu_.isEmpty()) {
          cpu_ = other.cpu_;
          bitField0_ |= 0x00000004;
        } else {
          ensureCpuIsMutable();
          cpu_.addAll(other.cpu_);
        }
        onChanged();
      }
      if (other.getMemTotal() != 0L) {
        setMemTotal(other.getMemTotal());
      }
      if (other.getDiskTotal() != 0L) {
        setDiskTotal(other.getDiskTotal());
      }
      if (other.getSwapTotal() != 0L) {
        setSwapTotal(other.getSwapTotal());
      }
      if (!other.getArch().isEmpty()) {
        arch_ = other.arch_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getVirtualization().isEmpty()) {
        virtualization_ = other.virtualization_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getBootTime() != 0L) {
        setBootTime(other.getBootTime());
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.gpu_.isEmpty()) {
        if (gpu_.isEmpty()) {
          gpu_ = other.gpu_;
          bitField0_ |= 0x00000400;
        } else {
          ensureGpuIsMutable();
          gpu_.addAll(other.gpu_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              platform_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              platformVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCpuIsMutable();
              cpu_.add(s);
              break;
            } // case 26
            case 32: {
              memTotal_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              diskTotal_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              swapTotal_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              arch_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              virtualization_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              bootTime_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureGpuIsMutable();
              gpu_.add(s);
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object platform_ = "";
    /**
     * <code>string platform = 1;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform = 1;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform = 1;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      platform_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      platform_ = getDefaultInstance().getPlatform();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 1;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      platform_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object platformVersion_ = "";
    /**
     * <code>string platform_version = 2;</code>
     * @return The platformVersion.
     */
    public java.lang.String getPlatformVersion() {
      java.lang.Object ref = platformVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform_version = 2;</code>
     * @return The bytes for platformVersion.
     */
    public com.google.protobuf.ByteString
        getPlatformVersionBytes() {
      java.lang.Object ref = platformVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform_version = 2;</code>
     * @param value The platformVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      platformVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string platform_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformVersion() {
      platformVersion_ = getDefaultInstance().getPlatformVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string platform_version = 2;</code>
     * @param value The bytes for platformVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      platformVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList cpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCpuIsMutable() {
      if (!cpu_.isModifiable()) {
        cpu_ = new com.google.protobuf.LazyStringArrayList(cpu_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @return A list containing the cpu.
     */
    public com.google.protobuf.ProtocolStringList
        getCpuList() {
      cpu_.makeImmutable();
      return cpu_;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @return The count of cpu.
     */
    public int getCpuCount() {
      return cpu_.size();
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param index The index of the element to return.
     * @return The cpu at the given index.
     */
    public java.lang.String getCpu(int index) {
      return cpu_.get(index);
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cpu at the given index.
     */
    public com.google.protobuf.ByteString
        getCpuBytes(int index) {
      return cpu_.getByteString(index);
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param index The index to set the value at.
     * @param value The cpu to set.
     * @return This builder for chaining.
     */
    public Builder setCpu(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCpuIsMutable();
      cpu_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param value The cpu to add.
     * @return This builder for chaining.
     */
    public Builder addCpu(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCpuIsMutable();
      cpu_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param values The cpu to add.
     * @return This builder for chaining.
     */
    public Builder addAllCpu(
        java.lang.Iterable<java.lang.String> values) {
      ensureCpuIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cpu_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpu() {
      cpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cpu = 3;</code>
     * @param value The bytes of the cpu to add.
     * @return This builder for chaining.
     */
    public Builder addCpuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCpuIsMutable();
      cpu_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long memTotal_ ;
    /**
     * <code>uint64 mem_total = 4;</code>
     * @return The memTotal.
     */
    @java.lang.Override
    public long getMemTotal() {
      return memTotal_;
    }
    /**
     * <code>uint64 mem_total = 4;</code>
     * @param value The memTotal to set.
     * @return This builder for chaining.
     */
    public Builder setMemTotal(long value) {

      memTotal_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 mem_total = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemTotal() {
      bitField0_ = (bitField0_ & ~0x00000008);
      memTotal_ = 0L;
      onChanged();
      return this;
    }

    private long diskTotal_ ;
    /**
     * <code>uint64 disk_total = 5;</code>
     * @return The diskTotal.
     */
    @java.lang.Override
    public long getDiskTotal() {
      return diskTotal_;
    }
    /**
     * <code>uint64 disk_total = 5;</code>
     * @param value The diskTotal to set.
     * @return This builder for chaining.
     */
    public Builder setDiskTotal(long value) {

      diskTotal_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 disk_total = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiskTotal() {
      bitField0_ = (bitField0_ & ~0x00000010);
      diskTotal_ = 0L;
      onChanged();
      return this;
    }

    private long swapTotal_ ;
    /**
     * <code>uint64 swap_total = 6;</code>
     * @return The swapTotal.
     */
    @java.lang.Override
    public long getSwapTotal() {
      return swapTotal_;
    }
    /**
     * <code>uint64 swap_total = 6;</code>
     * @param value The swapTotal to set.
     * @return This builder for chaining.
     */
    public Builder setSwapTotal(long value) {

      swapTotal_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 swap_total = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSwapTotal() {
      bitField0_ = (bitField0_ & ~0x00000020);
      swapTotal_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object arch_ = "";
    /**
     * <code>string arch = 7;</code>
     * @return The arch.
     */
    public java.lang.String getArch() {
      java.lang.Object ref = arch_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arch_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arch = 7;</code>
     * @return The bytes for arch.
     */
    public com.google.protobuf.ByteString
        getArchBytes() {
      java.lang.Object ref = arch_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arch = 7;</code>
     * @param value The arch to set.
     * @return This builder for chaining.
     */
    public Builder setArch(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      arch_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string arch = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearArch() {
      arch_ = getDefaultInstance().getArch();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string arch = 7;</code>
     * @param value The bytes for arch to set.
     * @return This builder for chaining.
     */
    public Builder setArchBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      arch_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object virtualization_ = "";
    /**
     * <code>string virtualization = 8;</code>
     * @return The virtualization.
     */
    public java.lang.String getVirtualization() {
      java.lang.Object ref = virtualization_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        virtualization_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string virtualization = 8;</code>
     * @return The bytes for virtualization.
     */
    public com.google.protobuf.ByteString
        getVirtualizationBytes() {
      java.lang.Object ref = virtualization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        virtualization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string virtualization = 8;</code>
     * @param value The virtualization to set.
     * @return This builder for chaining.
     */
    public Builder setVirtualization(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      virtualization_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string virtualization = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVirtualization() {
      virtualization_ = getDefaultInstance().getVirtualization();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string virtualization = 8;</code>
     * @param value The bytes for virtualization to set.
     * @return This builder for chaining.
     */
    public Builder setVirtualizationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      virtualization_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long bootTime_ ;
    /**
     * <code>uint64 boot_time = 9;</code>
     * @return The bootTime.
     */
    @java.lang.Override
    public long getBootTime() {
      return bootTime_;
    }
    /**
     * <code>uint64 boot_time = 9;</code>
     * @param value The bootTime to set.
     * @return This builder for chaining.
     */
    public Builder setBootTime(long value) {

      bootTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 boot_time = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBootTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      bootTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 10;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 10;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 10;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 10;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList gpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureGpuIsMutable() {
      if (!gpu_.isModifiable()) {
        gpu_ = new com.google.protobuf.LazyStringArrayList(gpu_);
      }
      bitField0_ |= 0x00000400;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @return A list containing the gpu.
     */
    public com.google.protobuf.ProtocolStringList
        getGpuList() {
      gpu_.makeImmutable();
      return gpu_;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @return The count of gpu.
     */
    public int getGpuCount() {
      return gpu_.size();
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param index The index of the element to return.
     * @return The gpu at the given index.
     */
    public java.lang.String getGpu(int index) {
      return gpu_.get(index);
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the gpu at the given index.
     */
    public com.google.protobuf.ByteString
        getGpuBytes(int index) {
      return gpu_.getByteString(index);
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param index The index to set the value at.
     * @param value The gpu to set.
     * @return This builder for chaining.
     */
    public Builder setGpu(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGpuIsMutable();
      gpu_.set(index, value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param value The gpu to add.
     * @return This builder for chaining.
     */
    public Builder addGpu(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGpuIsMutable();
      gpu_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param values The gpu to add.
     * @return This builder for chaining.
     */
    public Builder addAllGpu(
        java.lang.Iterable<java.lang.String> values) {
      ensureGpuIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, gpu_);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearGpu() {
      gpu_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gpu = 11;</code>
     * @param value The bytes of the gpu to add.
     * @return This builder for chaining.
     */
    public Builder addGpuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureGpuIsMutable();
      gpu_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Host)
  }

  // @@protoc_insertion_point(class_scope:proto.Host)
  private static final com.nezhahq.agent.proto.Host DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nezhahq.agent.proto.Host();
  }

  public static com.nezhahq.agent.proto.Host getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Host>
      PARSER = new com.google.protobuf.AbstractParser<Host>() {
    @java.lang.Override
    public Host parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Host> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Host> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nezhahq.agent.proto.Host getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

