// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface IOStreamDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.IOStreamData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
