// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

/**
 * Protobuf type {@code proto.IP}
 */
public final class IP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.IP)
    IPOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IP.newBuilder() to construct.
  private IP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IP() {
    ipv4_ = "";
    ipv6_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IP();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_IP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_IP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nezhahq.agent.proto.IP.class, com.nezhahq.agent.proto.IP.Builder.class);
  }

  public static final int IPV4_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipv4_ = "";
  /**
   * <code>string ipv4 = 1;</code>
   * @return The ipv4.
   */
  @java.lang.Override
  public java.lang.String getIpv4() {
    java.lang.Object ref = ipv4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv4_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv4 = 1;</code>
   * @return The bytes for ipv4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpv4Bytes() {
    java.lang.Object ref = ipv4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPV6_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipv6_ = "";
  /**
   * <code>string ipv6 = 2;</code>
   * @return The ipv6.
   */
  @java.lang.Override
  public java.lang.String getIpv6() {
    java.lang.Object ref = ipv6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv6_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv6 = 2;</code>
   * @return The bytes for ipv6.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpv6Bytes() {
    java.lang.Object ref = ipv6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv4_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipv4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv6_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ipv6_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv4_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipv4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv6_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ipv6_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nezhahq.agent.proto.IP)) {
      return super.equals(obj);
    }
    com.nezhahq.agent.proto.IP other = (com.nezhahq.agent.proto.IP) obj;

    if (!getIpv4()
        .equals(other.getIpv4())) return false;
    if (!getIpv6()
        .equals(other.getIpv6())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IPV4_FIELD_NUMBER;
    hash = (53 * hash) + getIpv4().hashCode();
    hash = (37 * hash) + IPV6_FIELD_NUMBER;
    hash = (53 * hash) + getIpv6().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nezhahq.agent.proto.IP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nezhahq.agent.proto.IP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nezhahq.agent.proto.IP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.IP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nezhahq.agent.proto.IP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.IP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.IP)
      com.nezhahq.agent.proto.IPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_IP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_IP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nezhahq.agent.proto.IP.class, com.nezhahq.agent.proto.IP.Builder.class);
    }

    // Construct using com.nezhahq.agent.proto.IP.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ipv4_ = "";
      ipv6_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_IP_descriptor;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.IP getDefaultInstanceForType() {
      return com.nezhahq.agent.proto.IP.getDefaultInstance();
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.IP build() {
      com.nezhahq.agent.proto.IP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.IP buildPartial() {
      com.nezhahq.agent.proto.IP result = new com.nezhahq.agent.proto.IP(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nezhahq.agent.proto.IP result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ipv4_ = ipv4_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ipv6_ = ipv6_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nezhahq.agent.proto.IP) {
        return mergeFrom((com.nezhahq.agent.proto.IP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nezhahq.agent.proto.IP other) {
      if (other == com.nezhahq.agent.proto.IP.getDefaultInstance()) return this;
      if (!other.getIpv4().isEmpty()) {
        ipv4_ = other.ipv4_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIpv6().isEmpty()) {
        ipv6_ = other.ipv6_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ipv4_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ipv6_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ipv4_ = "";
    /**
     * <code>string ipv4 = 1;</code>
     * @return The ipv4.
     */
    public java.lang.String getIpv4() {
      java.lang.Object ref = ipv4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv4 = 1;</code>
     * @return The bytes for ipv4.
     */
    public com.google.protobuf.ByteString
        getIpv4Bytes() {
      java.lang.Object ref = ipv4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv4 = 1;</code>
     * @param value The ipv4 to set.
     * @return This builder for chaining.
     */
    public Builder setIpv4(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipv4_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIpv4() {
      ipv4_ = getDefaultInstance().getIpv4();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4 = 1;</code>
     * @param value The bytes for ipv4 to set.
     * @return This builder for chaining.
     */
    public Builder setIpv4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipv4_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object ipv6_ = "";
    /**
     * <code>string ipv6 = 2;</code>
     * @return The ipv6.
     */
    public java.lang.String getIpv6() {
      java.lang.Object ref = ipv6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv6 = 2;</code>
     * @return The bytes for ipv6.
     */
    public com.google.protobuf.ByteString
        getIpv6Bytes() {
      java.lang.Object ref = ipv6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv6 = 2;</code>
     * @param value The ipv6 to set.
     * @return This builder for chaining.
     */
    public Builder setIpv6(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipv6_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIpv6() {
      ipv6_ = getDefaultInstance().getIpv6();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6 = 2;</code>
     * @param value The bytes for ipv6 to set.
     * @return This builder for chaining.
     */
    public Builder setIpv6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipv6_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.IP)
  }

  // @@protoc_insertion_point(class_scope:proto.IP)
  private static final com.nezhahq.agent.proto.IP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nezhahq.agent.proto.IP();
  }

  public static com.nezhahq.agent.proto.IP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IP>
      PARSER = new com.google.protobuf.AbstractParser<IP>() {
    @java.lang.Override
    public IP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nezhahq.agent.proto.IP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

