// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface IPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.IP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ipv4 = 1;</code>
   * @return The ipv4.
   */
  java.lang.String getIpv4();
  /**
   * <code>string ipv4 = 1;</code>
   * @return The bytes for ipv4.
   */
  com.google.protobuf.ByteString
      getIpv4Bytes();

  /**
   * <code>string ipv6 = 2;</code>
   * @return The ipv6.
   */
  java.lang.String getIpv6();
  /**
   * <code>string ipv6 = 2;</code>
   * @return The bytes for ipv6.
   */
  com.google.protobuf.ByteString
      getIpv6Bytes();
}
