// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public final class NezhaProto {
  private NezhaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Host_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Host_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_State_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_State_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_State_SensorTemperature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_State_SensorTemperature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TaskResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TaskResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Receipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Receipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Uint64Receipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Uint64Receipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_IOStreamData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_IOStreamData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GeoIP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GeoIP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_IP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_IP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013nezha.proto\022\005proto\"\321\001\n\004Host\022\020\n\010platfor" +
      "m\030\001 \001(\t\022\030\n\020platform_version\030\002 \001(\t\022\013\n\003cpu" +
      "\030\003 \003(\t\022\021\n\tmem_total\030\004 \001(\004\022\022\n\ndisk_total\030" +
      "\005 \001(\004\022\022\n\nswap_total\030\006 \001(\004\022\014\n\004arch\030\007 \001(\t\022" +
      "\026\n\016virtualization\030\010 \001(\t\022\021\n\tboot_time\030\t \001" +
      "(\004\022\017\n\007version\030\n \001(\t\022\013\n\003gpu\030\013 \003(\t\"\364\002\n\005Sta" +
      "te\022\013\n\003cpu\030\001 \001(\001\022\020\n\010mem_used\030\002 \001(\004\022\021\n\tswa" +
      "p_used\030\003 \001(\004\022\021\n\tdisk_used\030\004 \001(\004\022\027\n\017net_i" +
      "n_transfer\030\005 \001(\004\022\030\n\020net_out_transfer\030\006 \001" +
      "(\004\022\024\n\014net_in_speed\030\007 \001(\004\022\025\n\rnet_out_spee" +
      "d\030\010 \001(\004\022\016\n\006uptime\030\t \001(\004\022\r\n\005load1\030\n \001(\001\022\r" +
      "\n\005load5\030\013 \001(\001\022\016\n\006load15\030\014 \001(\001\022\026\n\016tcp_con" +
      "n_count\030\r \001(\004\022\026\n\016udp_conn_count\030\016 \001(\004\022\025\n" +
      "\rprocess_count\030\017 \001(\004\0224\n\014temperatures\030\020 \003" +
      "(\0132\036.proto.State_SensorTemperature\022\013\n\003gp" +
      "u\030\021 \003(\001\"<\n\027State_SensorTemperature\022\014\n\004na" +
      "me\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\001\".\n\004Task\022\n\n" +
      "\002id\030\001 \001(\004\022\014\n\004type\030\002 \001(\004\022\014\n\004data\030\003 \001(\t\"W\n" +
      "\nTaskResult\022\n\n\002id\030\001 \001(\004\022\014\n\004type\030\002 \001(\004\022\r\n" +
      "\005delay\030\003 \001(\002\022\014\n\004data\030\004 \001(\t\022\022\n\nsuccessful" +
      "\030\005 \001(\010\"\031\n\007Receipt\022\016\n\006proced\030\001 \001(\010\"\035\n\rUin" +
      "t64Receipt\022\014\n\004data\030\001 \001(\004\"\034\n\014IOStreamData" +
      "\022\014\n\004data\030\001 \001(\014\"_\n\005GeoIP\022\014\n\004use6\030\001 \001(\010\022\025\n" +
      "\002ip\030\002 \001(\0132\t.proto.IP\022\024\n\014country_code\030\003 \001" +
      "(\t\022\033\n\023dashboard_boot_time\030\004 \001(\004\" \n\002IP\022\014\n" +
      "\004ipv4\030\001 \001(\t\022\014\n\004ipv6\030\002 \001(\t2\322\002\n\014NezhaServi" +
      "ce\0227\n\021ReportSystemState\022\014.proto.State\032\016." +
      "proto.Receipt\"\000(\0010\001\0221\n\020ReportSystemInfo\022" +
      "\013.proto.Host\032\016.proto.Receipt\"\000\0223\n\013Reques" +
      "tTask\022\021.proto.TaskResult\032\013.proto.Task\"\000(" +
      "\0010\001\022:\n\010IOStream\022\023.proto.IOStreamData\032\023.p" +
      "roto.IOStreamData\"\000(\0010\001\022+\n\013ReportGeoIP\022\014" +
      ".proto.GeoIP\032\014.proto.GeoIP\"\000\0228\n\021ReportSy" +
      "stemInfo2\022\013.proto.Host\032\024.proto.Uint64Rec" +
      "eipt\"\000B\'\n\027com.nezhahq.agent.protoB\nNezha" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Host_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Host_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Host_descriptor,
        new java.lang.String[] { "Platform", "PlatformVersion", "Cpu", "MemTotal", "DiskTotal", "SwapTotal", "Arch", "Virtualization", "BootTime", "Version", "Gpu", });
    internal_static_proto_State_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_State_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_State_descriptor,
        new java.lang.String[] { "Cpu", "MemUsed", "SwapUsed", "DiskUsed", "NetInTransfer", "NetOutTransfer", "NetInSpeed", "NetOutSpeed", "Uptime", "Load1", "Load5", "Load15", "TcpConnCount", "UdpConnCount", "ProcessCount", "Temperatures", "Gpu", });
    internal_static_proto_State_SensorTemperature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_State_SensorTemperature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_State_SensorTemperature_descriptor,
        new java.lang.String[] { "Name", "Temperature", });
    internal_static_proto_Task_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Task_descriptor,
        new java.lang.String[] { "Id", "Type", "Data", });
    internal_static_proto_TaskResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_TaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TaskResult_descriptor,
        new java.lang.String[] { "Id", "Type", "Delay", "Data", "Successful", });
    internal_static_proto_Receipt_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_Receipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Receipt_descriptor,
        new java.lang.String[] { "Proced", });
    internal_static_proto_Uint64Receipt_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_Uint64Receipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Uint64Receipt_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_proto_IOStreamData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_IOStreamData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_IOStreamData_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_proto_GeoIP_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_GeoIP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GeoIP_descriptor,
        new java.lang.String[] { "Use6", "Ip", "CountryCode", "DashboardBootTime", });
    internal_static_proto_IP_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_IP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_IP_descriptor,
        new java.lang.String[] { "Ipv4", "Ipv6", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
