// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool proced = 1;</code>
   * @return The proced.
   */
  boolean getProced();
}
