// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

/**
 * Protobuf type {@code proto.State}
 */
public final class State extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.State)
    StateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use State.newBuilder() to construct.
  private State(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private State() {
    temperatures_ = java.util.Collections.emptyList();
    gpu_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new State();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_State_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_State_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nezhahq.agent.proto.State.class, com.nezhahq.agent.proto.State.Builder.class);
  }

  public static final int CPU_FIELD_NUMBER = 1;
  private double cpu_ = 0D;
  /**
   * <code>double cpu = 1;</code>
   * @return The cpu.
   */
  @java.lang.Override
  public double getCpu() {
    return cpu_;
  }

  public static final int MEM_USED_FIELD_NUMBER = 2;
  private long memUsed_ = 0L;
  /**
   * <code>uint64 mem_used = 2;</code>
   * @return The memUsed.
   */
  @java.lang.Override
  public long getMemUsed() {
    return memUsed_;
  }

  public static final int SWAP_USED_FIELD_NUMBER = 3;
  private long swapUsed_ = 0L;
  /**
   * <code>uint64 swap_used = 3;</code>
   * @return The swapUsed.
   */
  @java.lang.Override
  public long getSwapUsed() {
    return swapUsed_;
  }

  public static final int DISK_USED_FIELD_NUMBER = 4;
  private long diskUsed_ = 0L;
  /**
   * <code>uint64 disk_used = 4;</code>
   * @return The diskUsed.
   */
  @java.lang.Override
  public long getDiskUsed() {
    return diskUsed_;
  }

  public static final int NET_IN_TRANSFER_FIELD_NUMBER = 5;
  private long netInTransfer_ = 0L;
  /**
   * <code>uint64 net_in_transfer = 5;</code>
   * @return The netInTransfer.
   */
  @java.lang.Override
  public long getNetInTransfer() {
    return netInTransfer_;
  }

  public static final int NET_OUT_TRANSFER_FIELD_NUMBER = 6;
  private long netOutTransfer_ = 0L;
  /**
   * <code>uint64 net_out_transfer = 6;</code>
   * @return The netOutTransfer.
   */
  @java.lang.Override
  public long getNetOutTransfer() {
    return netOutTransfer_;
  }

  public static final int NET_IN_SPEED_FIELD_NUMBER = 7;
  private long netInSpeed_ = 0L;
  /**
   * <code>uint64 net_in_speed = 7;</code>
   * @return The netInSpeed.
   */
  @java.lang.Override
  public long getNetInSpeed() {
    return netInSpeed_;
  }

  public static final int NET_OUT_SPEED_FIELD_NUMBER = 8;
  private long netOutSpeed_ = 0L;
  /**
   * <code>uint64 net_out_speed = 8;</code>
   * @return The netOutSpeed.
   */
  @java.lang.Override
  public long getNetOutSpeed() {
    return netOutSpeed_;
  }

  public static final int UPTIME_FIELD_NUMBER = 9;
  private long uptime_ = 0L;
  /**
   * <code>uint64 uptime = 9;</code>
   * @return The uptime.
   */
  @java.lang.Override
  public long getUptime() {
    return uptime_;
  }

  public static final int LOAD1_FIELD_NUMBER = 10;
  private double load1_ = 0D;
  /**
   * <code>double load1 = 10;</code>
   * @return The load1.
   */
  @java.lang.Override
  public double getLoad1() {
    return load1_;
  }

  public static final int LOAD5_FIELD_NUMBER = 11;
  private double load5_ = 0D;
  /**
   * <code>double load5 = 11;</code>
   * @return The load5.
   */
  @java.lang.Override
  public double getLoad5() {
    return load5_;
  }

  public static final int LOAD15_FIELD_NUMBER = 12;
  private double load15_ = 0D;
  /**
   * <code>double load15 = 12;</code>
   * @return The load15.
   */
  @java.lang.Override
  public double getLoad15() {
    return load15_;
  }

  public static final int TCP_CONN_COUNT_FIELD_NUMBER = 13;
  private long tcpConnCount_ = 0L;
  /**
   * <code>uint64 tcp_conn_count = 13;</code>
   * @return The tcpConnCount.
   */
  @java.lang.Override
  public long getTcpConnCount() {
    return tcpConnCount_;
  }

  public static final int UDP_CONN_COUNT_FIELD_NUMBER = 14;
  private long udpConnCount_ = 0L;
  /**
   * <code>uint64 udp_conn_count = 14;</code>
   * @return The udpConnCount.
   */
  @java.lang.Override
  public long getUdpConnCount() {
    return udpConnCount_;
  }

  public static final int PROCESS_COUNT_FIELD_NUMBER = 15;
  private long processCount_ = 0L;
  /**
   * <code>uint64 process_count = 15;</code>
   * @return The processCount.
   */
  @java.lang.Override
  public long getProcessCount() {
    return processCount_;
  }

  public static final int TEMPERATURES_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private java.util.List<com.nezhahq.agent.proto.State_SensorTemperature> temperatures_;
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  @java.lang.Override
  public java.util.List<com.nezhahq.agent.proto.State_SensorTemperature> getTemperaturesList() {
    return temperatures_;
  }
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder> 
      getTemperaturesOrBuilderList() {
    return temperatures_;
  }
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  @java.lang.Override
  public int getTemperaturesCount() {
    return temperatures_.size();
  }
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  @java.lang.Override
  public com.nezhahq.agent.proto.State_SensorTemperature getTemperatures(int index) {
    return temperatures_.get(index);
  }
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  @java.lang.Override
  public com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder getTemperaturesOrBuilder(
      int index) {
    return temperatures_.get(index);
  }

  public static final int GPU_FIELD_NUMBER = 17;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList gpu_ =
      emptyDoubleList();
  /**
   * <code>repeated double gpu = 17;</code>
   * @return A list containing the gpu.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getGpuList() {
    return gpu_;
  }
  /**
   * <code>repeated double gpu = 17;</code>
   * @return The count of gpu.
   */
  public int getGpuCount() {
    return gpu_.size();
  }
  /**
   * <code>repeated double gpu = 17;</code>
   * @param index The index of the element to return.
   * @return The gpu at the given index.
   */
  public double getGpu(int index) {
    return gpu_.getDouble(index);
  }
  private int gpuMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (java.lang.Double.doubleToRawLongBits(cpu_) != 0) {
      output.writeDouble(1, cpu_);
    }
    if (memUsed_ != 0L) {
      output.writeUInt64(2, memUsed_);
    }
    if (swapUsed_ != 0L) {
      output.writeUInt64(3, swapUsed_);
    }
    if (diskUsed_ != 0L) {
      output.writeUInt64(4, diskUsed_);
    }
    if (netInTransfer_ != 0L) {
      output.writeUInt64(5, netInTransfer_);
    }
    if (netOutTransfer_ != 0L) {
      output.writeUInt64(6, netOutTransfer_);
    }
    if (netInSpeed_ != 0L) {
      output.writeUInt64(7, netInSpeed_);
    }
    if (netOutSpeed_ != 0L) {
      output.writeUInt64(8, netOutSpeed_);
    }
    if (uptime_ != 0L) {
      output.writeUInt64(9, uptime_);
    }
    if (java.lang.Double.doubleToRawLongBits(load1_) != 0) {
      output.writeDouble(10, load1_);
    }
    if (java.lang.Double.doubleToRawLongBits(load5_) != 0) {
      output.writeDouble(11, load5_);
    }
    if (java.lang.Double.doubleToRawLongBits(load15_) != 0) {
      output.writeDouble(12, load15_);
    }
    if (tcpConnCount_ != 0L) {
      output.writeUInt64(13, tcpConnCount_);
    }
    if (udpConnCount_ != 0L) {
      output.writeUInt64(14, udpConnCount_);
    }
    if (processCount_ != 0L) {
      output.writeUInt64(15, processCount_);
    }
    for (int i = 0; i < temperatures_.size(); i++) {
      output.writeMessage(16, temperatures_.get(i));
    }
    if (getGpuList().size() > 0) {
      output.writeUInt32NoTag(138);
      output.writeUInt32NoTag(gpuMemoizedSerializedSize);
    }
    for (int i = 0; i < gpu_.size(); i++) {
      output.writeDoubleNoTag(gpu_.getDouble(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(cpu_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, cpu_);
    }
    if (memUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, memUsed_);
    }
    if (swapUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, swapUsed_);
    }
    if (diskUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, diskUsed_);
    }
    if (netInTransfer_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, netInTransfer_);
    }
    if (netOutTransfer_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, netOutTransfer_);
    }
    if (netInSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, netInSpeed_);
    }
    if (netOutSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, netOutSpeed_);
    }
    if (uptime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, uptime_);
    }
    if (java.lang.Double.doubleToRawLongBits(load1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, load1_);
    }
    if (java.lang.Double.doubleToRawLongBits(load5_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, load5_);
    }
    if (java.lang.Double.doubleToRawLongBits(load15_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, load15_);
    }
    if (tcpConnCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, tcpConnCount_);
    }
    if (udpConnCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, udpConnCount_);
    }
    if (processCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(15, processCount_);
    }
    for (int i = 0; i < temperatures_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, temperatures_.get(i));
    }
    {
      int dataSize = 0;
      dataSize = 8 * getGpuList().size();
      size += dataSize;
      if (!getGpuList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      gpuMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nezhahq.agent.proto.State)) {
      return super.equals(obj);
    }
    com.nezhahq.agent.proto.State other = (com.nezhahq.agent.proto.State) obj;

    if (java.lang.Double.doubleToLongBits(getCpu())
        != java.lang.Double.doubleToLongBits(
            other.getCpu())) return false;
    if (getMemUsed()
        != other.getMemUsed()) return false;
    if (getSwapUsed()
        != other.getSwapUsed()) return false;
    if (getDiskUsed()
        != other.getDiskUsed()) return false;
    if (getNetInTransfer()
        != other.getNetInTransfer()) return false;
    if (getNetOutTransfer()
        != other.getNetOutTransfer()) return false;
    if (getNetInSpeed()
        != other.getNetInSpeed()) return false;
    if (getNetOutSpeed()
        != other.getNetOutSpeed()) return false;
    if (getUptime()
        != other.getUptime()) return false;
    if (java.lang.Double.doubleToLongBits(getLoad1())
        != java.lang.Double.doubleToLongBits(
            other.getLoad1())) return false;
    if (java.lang.Double.doubleToLongBits(getLoad5())
        != java.lang.Double.doubleToLongBits(
            other.getLoad5())) return false;
    if (java.lang.Double.doubleToLongBits(getLoad15())
        != java.lang.Double.doubleToLongBits(
            other.getLoad15())) return false;
    if (getTcpConnCount()
        != other.getTcpConnCount()) return false;
    if (getUdpConnCount()
        != other.getUdpConnCount()) return false;
    if (getProcessCount()
        != other.getProcessCount()) return false;
    if (!getTemperaturesList()
        .equals(other.getTemperaturesList())) return false;
    if (!getGpuList()
        .equals(other.getGpuList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CPU_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCpu()));
    hash = (37 * hash) + MEM_USED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemUsed());
    hash = (37 * hash) + SWAP_USED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSwapUsed());
    hash = (37 * hash) + DISK_USED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDiskUsed());
    hash = (37 * hash) + NET_IN_TRANSFER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNetInTransfer());
    hash = (37 * hash) + NET_OUT_TRANSFER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNetOutTransfer());
    hash = (37 * hash) + NET_IN_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNetInSpeed());
    hash = (37 * hash) + NET_OUT_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNetOutSpeed());
    hash = (37 * hash) + UPTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUptime());
    hash = (37 * hash) + LOAD1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLoad1()));
    hash = (37 * hash) + LOAD5_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLoad5()));
    hash = (37 * hash) + LOAD15_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLoad15()));
    hash = (37 * hash) + TCP_CONN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTcpConnCount());
    hash = (37 * hash) + UDP_CONN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUdpConnCount());
    hash = (37 * hash) + PROCESS_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProcessCount());
    if (getTemperaturesCount() > 0) {
      hash = (37 * hash) + TEMPERATURES_FIELD_NUMBER;
      hash = (53 * hash) + getTemperaturesList().hashCode();
    }
    if (getGpuCount() > 0) {
      hash = (37 * hash) + GPU_FIELD_NUMBER;
      hash = (53 * hash) + getGpuList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nezhahq.agent.proto.State parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.State parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.State parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nezhahq.agent.proto.State parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nezhahq.agent.proto.State parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nezhahq.agent.proto.State parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nezhahq.agent.proto.State prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.State}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.State)
      com.nezhahq.agent.proto.StateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_State_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_State_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nezhahq.agent.proto.State.class, com.nezhahq.agent.proto.State.Builder.class);
    }

    // Construct using com.nezhahq.agent.proto.State.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cpu_ = 0D;
      memUsed_ = 0L;
      swapUsed_ = 0L;
      diskUsed_ = 0L;
      netInTransfer_ = 0L;
      netOutTransfer_ = 0L;
      netInSpeed_ = 0L;
      netOutSpeed_ = 0L;
      uptime_ = 0L;
      load1_ = 0D;
      load5_ = 0D;
      load15_ = 0D;
      tcpConnCount_ = 0L;
      udpConnCount_ = 0L;
      processCount_ = 0L;
      if (temperaturesBuilder_ == null) {
        temperatures_ = java.util.Collections.emptyList();
      } else {
        temperatures_ = null;
        temperaturesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00008000);
      gpu_ = emptyDoubleList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nezhahq.agent.proto.NezhaProto.internal_static_proto_State_descriptor;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.State getDefaultInstanceForType() {
      return com.nezhahq.agent.proto.State.getDefaultInstance();
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.State build() {
      com.nezhahq.agent.proto.State result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nezhahq.agent.proto.State buildPartial() {
      com.nezhahq.agent.proto.State result = new com.nezhahq.agent.proto.State(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.nezhahq.agent.proto.State result) {
      if (temperaturesBuilder_ == null) {
        if (((bitField0_ & 0x00008000) != 0)) {
          temperatures_ = java.util.Collections.unmodifiableList(temperatures_);
          bitField0_ = (bitField0_ & ~0x00008000);
        }
        result.temperatures_ = temperatures_;
      } else {
        result.temperatures_ = temperaturesBuilder_.build();
      }
    }

    private void buildPartial0(com.nezhahq.agent.proto.State result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cpu_ = cpu_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.memUsed_ = memUsed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.swapUsed_ = swapUsed_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.diskUsed_ = diskUsed_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.netInTransfer_ = netInTransfer_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.netOutTransfer_ = netOutTransfer_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.netInSpeed_ = netInSpeed_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.netOutSpeed_ = netOutSpeed_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.uptime_ = uptime_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.load1_ = load1_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.load5_ = load5_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.load15_ = load15_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.tcpConnCount_ = tcpConnCount_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.udpConnCount_ = udpConnCount_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.processCount_ = processCount_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        gpu_.makeImmutable();
        result.gpu_ = gpu_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nezhahq.agent.proto.State) {
        return mergeFrom((com.nezhahq.agent.proto.State)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nezhahq.agent.proto.State other) {
      if (other == com.nezhahq.agent.proto.State.getDefaultInstance()) return this;
      if (other.getCpu() != 0D) {
        setCpu(other.getCpu());
      }
      if (other.getMemUsed() != 0L) {
        setMemUsed(other.getMemUsed());
      }
      if (other.getSwapUsed() != 0L) {
        setSwapUsed(other.getSwapUsed());
      }
      if (other.getDiskUsed() != 0L) {
        setDiskUsed(other.getDiskUsed());
      }
      if (other.getNetInTransfer() != 0L) {
        setNetInTransfer(other.getNetInTransfer());
      }
      if (other.getNetOutTransfer() != 0L) {
        setNetOutTransfer(other.getNetOutTransfer());
      }
      if (other.getNetInSpeed() != 0L) {
        setNetInSpeed(other.getNetInSpeed());
      }
      if (other.getNetOutSpeed() != 0L) {
        setNetOutSpeed(other.getNetOutSpeed());
      }
      if (other.getUptime() != 0L) {
        setUptime(other.getUptime());
      }
      if (other.getLoad1() != 0D) {
        setLoad1(other.getLoad1());
      }
      if (other.getLoad5() != 0D) {
        setLoad5(other.getLoad5());
      }
      if (other.getLoad15() != 0D) {
        setLoad15(other.getLoad15());
      }
      if (other.getTcpConnCount() != 0L) {
        setTcpConnCount(other.getTcpConnCount());
      }
      if (other.getUdpConnCount() != 0L) {
        setUdpConnCount(other.getUdpConnCount());
      }
      if (other.getProcessCount() != 0L) {
        setProcessCount(other.getProcessCount());
      }
      if (temperaturesBuilder_ == null) {
        if (!other.temperatures_.isEmpty()) {
          if (temperatures_.isEmpty()) {
            temperatures_ = other.temperatures_;
            bitField0_ = (bitField0_ & ~0x00008000);
          } else {
            ensureTemperaturesIsMutable();
            temperatures_.addAll(other.temperatures_);
          }
          onChanged();
        }
      } else {
        if (!other.temperatures_.isEmpty()) {
          if (temperaturesBuilder_.isEmpty()) {
            temperaturesBuilder_.dispose();
            temperaturesBuilder_ = null;
            temperatures_ = other.temperatures_;
            bitField0_ = (bitField0_ & ~0x00008000);
            temperaturesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTemperaturesFieldBuilder() : null;
          } else {
            temperaturesBuilder_.addAllMessages(other.temperatures_);
          }
        }
      }
      if (!other.gpu_.isEmpty()) {
        if (gpu_.isEmpty()) {
          gpu_ = other.gpu_;
          gpu_.makeImmutable();
          bitField0_ |= 0x00010000;
        } else {
          ensureGpuIsMutable();
          gpu_.addAll(other.gpu_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              cpu_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 16: {
              memUsed_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              swapUsed_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              diskUsed_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              netInTransfer_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              netOutTransfer_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              netInSpeed_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              netOutSpeed_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              uptime_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 81: {
              load1_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 89: {
              load5_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 97: {
              load15_ = input.readDouble();
              bitField0_ |= 0x00000800;
              break;
            } // case 97
            case 104: {
              tcpConnCount_ = input.readUInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              udpConnCount_ = input.readUInt64();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              processCount_ = input.readUInt64();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 130: {
              com.nezhahq.agent.proto.State_SensorTemperature m =
                  input.readMessage(
                      com.nezhahq.agent.proto.State_SensorTemperature.parser(),
                      extensionRegistry);
              if (temperaturesBuilder_ == null) {
                ensureTemperaturesIsMutable();
                temperatures_.add(m);
              } else {
                temperaturesBuilder_.addMessage(m);
              }
              break;
            } // case 130
            case 137: {
              double v = input.readDouble();
              ensureGpuIsMutable();
              gpu_.addDouble(v);
              break;
            } // case 137
            case 138: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureGpuIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                gpu_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 138
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double cpu_ ;
    /**
     * <code>double cpu = 1;</code>
     * @return The cpu.
     */
    @java.lang.Override
    public double getCpu() {
      return cpu_;
    }
    /**
     * <code>double cpu = 1;</code>
     * @param value The cpu to set.
     * @return This builder for chaining.
     */
    public Builder setCpu(double value) {

      cpu_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double cpu = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpu() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cpu_ = 0D;
      onChanged();
      return this;
    }

    private long memUsed_ ;
    /**
     * <code>uint64 mem_used = 2;</code>
     * @return The memUsed.
     */
    @java.lang.Override
    public long getMemUsed() {
      return memUsed_;
    }
    /**
     * <code>uint64 mem_used = 2;</code>
     * @param value The memUsed to set.
     * @return This builder for chaining.
     */
    public Builder setMemUsed(long value) {

      memUsed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 mem_used = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemUsed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      memUsed_ = 0L;
      onChanged();
      return this;
    }

    private long swapUsed_ ;
    /**
     * <code>uint64 swap_used = 3;</code>
     * @return The swapUsed.
     */
    @java.lang.Override
    public long getSwapUsed() {
      return swapUsed_;
    }
    /**
     * <code>uint64 swap_used = 3;</code>
     * @param value The swapUsed to set.
     * @return This builder for chaining.
     */
    public Builder setSwapUsed(long value) {

      swapUsed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 swap_used = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSwapUsed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      swapUsed_ = 0L;
      onChanged();
      return this;
    }

    private long diskUsed_ ;
    /**
     * <code>uint64 disk_used = 4;</code>
     * @return The diskUsed.
     */
    @java.lang.Override
    public long getDiskUsed() {
      return diskUsed_;
    }
    /**
     * <code>uint64 disk_used = 4;</code>
     * @param value The diskUsed to set.
     * @return This builder for chaining.
     */
    public Builder setDiskUsed(long value) {

      diskUsed_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 disk_used = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiskUsed() {
      bitField0_ = (bitField0_ & ~0x00000008);
      diskUsed_ = 0L;
      onChanged();
      return this;
    }

    private long netInTransfer_ ;
    /**
     * <code>uint64 net_in_transfer = 5;</code>
     * @return The netInTransfer.
     */
    @java.lang.Override
    public long getNetInTransfer() {
      return netInTransfer_;
    }
    /**
     * <code>uint64 net_in_transfer = 5;</code>
     * @param value The netInTransfer to set.
     * @return This builder for chaining.
     */
    public Builder setNetInTransfer(long value) {

      netInTransfer_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 net_in_transfer = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetInTransfer() {
      bitField0_ = (bitField0_ & ~0x00000010);
      netInTransfer_ = 0L;
      onChanged();
      return this;
    }

    private long netOutTransfer_ ;
    /**
     * <code>uint64 net_out_transfer = 6;</code>
     * @return The netOutTransfer.
     */
    @java.lang.Override
    public long getNetOutTransfer() {
      return netOutTransfer_;
    }
    /**
     * <code>uint64 net_out_transfer = 6;</code>
     * @param value The netOutTransfer to set.
     * @return This builder for chaining.
     */
    public Builder setNetOutTransfer(long value) {

      netOutTransfer_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 net_out_transfer = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetOutTransfer() {
      bitField0_ = (bitField0_ & ~0x00000020);
      netOutTransfer_ = 0L;
      onChanged();
      return this;
    }

    private long netInSpeed_ ;
    /**
     * <code>uint64 net_in_speed = 7;</code>
     * @return The netInSpeed.
     */
    @java.lang.Override
    public long getNetInSpeed() {
      return netInSpeed_;
    }
    /**
     * <code>uint64 net_in_speed = 7;</code>
     * @param value The netInSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setNetInSpeed(long value) {

      netInSpeed_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 net_in_speed = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetInSpeed() {
      bitField0_ = (bitField0_ & ~0x00000040);
      netInSpeed_ = 0L;
      onChanged();
      return this;
    }

    private long netOutSpeed_ ;
    /**
     * <code>uint64 net_out_speed = 8;</code>
     * @return The netOutSpeed.
     */
    @java.lang.Override
    public long getNetOutSpeed() {
      return netOutSpeed_;
    }
    /**
     * <code>uint64 net_out_speed = 8;</code>
     * @param value The netOutSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setNetOutSpeed(long value) {

      netOutSpeed_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 net_out_speed = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetOutSpeed() {
      bitField0_ = (bitField0_ & ~0x00000080);
      netOutSpeed_ = 0L;
      onChanged();
      return this;
    }

    private long uptime_ ;
    /**
     * <code>uint64 uptime = 9;</code>
     * @return The uptime.
     */
    @java.lang.Override
    public long getUptime() {
      return uptime_;
    }
    /**
     * <code>uint64 uptime = 9;</code>
     * @param value The uptime to set.
     * @return This builder for chaining.
     */
    public Builder setUptime(long value) {

      uptime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uptime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      uptime_ = 0L;
      onChanged();
      return this;
    }

    private double load1_ ;
    /**
     * <code>double load1 = 10;</code>
     * @return The load1.
     */
    @java.lang.Override
    public double getLoad1() {
      return load1_;
    }
    /**
     * <code>double load1 = 10;</code>
     * @param value The load1 to set.
     * @return This builder for chaining.
     */
    public Builder setLoad1(double value) {

      load1_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>double load1 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoad1() {
      bitField0_ = (bitField0_ & ~0x00000200);
      load1_ = 0D;
      onChanged();
      return this;
    }

    private double load5_ ;
    /**
     * <code>double load5 = 11;</code>
     * @return The load5.
     */
    @java.lang.Override
    public double getLoad5() {
      return load5_;
    }
    /**
     * <code>double load5 = 11;</code>
     * @param value The load5 to set.
     * @return This builder for chaining.
     */
    public Builder setLoad5(double value) {

      load5_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>double load5 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoad5() {
      bitField0_ = (bitField0_ & ~0x00000400);
      load5_ = 0D;
      onChanged();
      return this;
    }

    private double load15_ ;
    /**
     * <code>double load15 = 12;</code>
     * @return The load15.
     */
    @java.lang.Override
    public double getLoad15() {
      return load15_;
    }
    /**
     * <code>double load15 = 12;</code>
     * @param value The load15 to set.
     * @return This builder for chaining.
     */
    public Builder setLoad15(double value) {

      load15_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>double load15 = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoad15() {
      bitField0_ = (bitField0_ & ~0x00000800);
      load15_ = 0D;
      onChanged();
      return this;
    }

    private long tcpConnCount_ ;
    /**
     * <code>uint64 tcp_conn_count = 13;</code>
     * @return The tcpConnCount.
     */
    @java.lang.Override
    public long getTcpConnCount() {
      return tcpConnCount_;
    }
    /**
     * <code>uint64 tcp_conn_count = 13;</code>
     * @param value The tcpConnCount to set.
     * @return This builder for chaining.
     */
    public Builder setTcpConnCount(long value) {

      tcpConnCount_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 tcp_conn_count = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearTcpConnCount() {
      bitField0_ = (bitField0_ & ~0x00001000);
      tcpConnCount_ = 0L;
      onChanged();
      return this;
    }

    private long udpConnCount_ ;
    /**
     * <code>uint64 udp_conn_count = 14;</code>
     * @return The udpConnCount.
     */
    @java.lang.Override
    public long getUdpConnCount() {
      return udpConnCount_;
    }
    /**
     * <code>uint64 udp_conn_count = 14;</code>
     * @param value The udpConnCount to set.
     * @return This builder for chaining.
     */
    public Builder setUdpConnCount(long value) {

      udpConnCount_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 udp_conn_count = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpConnCount() {
      bitField0_ = (bitField0_ & ~0x00002000);
      udpConnCount_ = 0L;
      onChanged();
      return this;
    }

    private long processCount_ ;
    /**
     * <code>uint64 process_count = 15;</code>
     * @return The processCount.
     */
    @java.lang.Override
    public long getProcessCount() {
      return processCount_;
    }
    /**
     * <code>uint64 process_count = 15;</code>
     * @param value The processCount to set.
     * @return This builder for chaining.
     */
    public Builder setProcessCount(long value) {

      processCount_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 process_count = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessCount() {
      bitField0_ = (bitField0_ & ~0x00004000);
      processCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.nezhahq.agent.proto.State_SensorTemperature> temperatures_ =
      java.util.Collections.emptyList();
    private void ensureTemperaturesIsMutable() {
      if (!((bitField0_ & 0x00008000) != 0)) {
        temperatures_ = new java.util.ArrayList<com.nezhahq.agent.proto.State_SensorTemperature>(temperatures_);
        bitField0_ |= 0x00008000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nezhahq.agent.proto.State_SensorTemperature, com.nezhahq.agent.proto.State_SensorTemperature.Builder, com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder> temperaturesBuilder_;

    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public java.util.List<com.nezhahq.agent.proto.State_SensorTemperature> getTemperaturesList() {
      if (temperaturesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(temperatures_);
      } else {
        return temperaturesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public int getTemperaturesCount() {
      if (temperaturesBuilder_ == null) {
        return temperatures_.size();
      } else {
        return temperaturesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public com.nezhahq.agent.proto.State_SensorTemperature getTemperatures(int index) {
      if (temperaturesBuilder_ == null) {
        return temperatures_.get(index);
      } else {
        return temperaturesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder setTemperatures(
        int index, com.nezhahq.agent.proto.State_SensorTemperature value) {
      if (temperaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemperaturesIsMutable();
        temperatures_.set(index, value);
        onChanged();
      } else {
        temperaturesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder setTemperatures(
        int index, com.nezhahq.agent.proto.State_SensorTemperature.Builder builderForValue) {
      if (temperaturesBuilder_ == null) {
        ensureTemperaturesIsMutable();
        temperatures_.set(index, builderForValue.build());
        onChanged();
      } else {
        temperaturesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder addTemperatures(com.nezhahq.agent.proto.State_SensorTemperature value) {
      if (temperaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemperaturesIsMutable();
        temperatures_.add(value);
        onChanged();
      } else {
        temperaturesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder addTemperatures(
        int index, com.nezhahq.agent.proto.State_SensorTemperature value) {
      if (temperaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTemperaturesIsMutable();
        temperatures_.add(index, value);
        onChanged();
      } else {
        temperaturesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder addTemperatures(
        com.nezhahq.agent.proto.State_SensorTemperature.Builder builderForValue) {
      if (temperaturesBuilder_ == null) {
        ensureTemperaturesIsMutable();
        temperatures_.add(builderForValue.build());
        onChanged();
      } else {
        temperaturesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder addTemperatures(
        int index, com.nezhahq.agent.proto.State_SensorTemperature.Builder builderForValue) {
      if (temperaturesBuilder_ == null) {
        ensureTemperaturesIsMutable();
        temperatures_.add(index, builderForValue.build());
        onChanged();
      } else {
        temperaturesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder addAllTemperatures(
        java.lang.Iterable<? extends com.nezhahq.agent.proto.State_SensorTemperature> values) {
      if (temperaturesBuilder_ == null) {
        ensureTemperaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, temperatures_);
        onChanged();
      } else {
        temperaturesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder clearTemperatures() {
      if (temperaturesBuilder_ == null) {
        temperatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
      } else {
        temperaturesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public Builder removeTemperatures(int index) {
      if (temperaturesBuilder_ == null) {
        ensureTemperaturesIsMutable();
        temperatures_.remove(index);
        onChanged();
      } else {
        temperaturesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public com.nezhahq.agent.proto.State_SensorTemperature.Builder getTemperaturesBuilder(
        int index) {
      return getTemperaturesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder getTemperaturesOrBuilder(
        int index) {
      if (temperaturesBuilder_ == null) {
        return temperatures_.get(index);  } else {
        return temperaturesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public java.util.List<? extends com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder> 
         getTemperaturesOrBuilderList() {
      if (temperaturesBuilder_ != null) {
        return temperaturesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(temperatures_);
      }
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public com.nezhahq.agent.proto.State_SensorTemperature.Builder addTemperaturesBuilder() {
      return getTemperaturesFieldBuilder().addBuilder(
          com.nezhahq.agent.proto.State_SensorTemperature.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public com.nezhahq.agent.proto.State_SensorTemperature.Builder addTemperaturesBuilder(
        int index) {
      return getTemperaturesFieldBuilder().addBuilder(
          index, com.nezhahq.agent.proto.State_SensorTemperature.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
     */
    public java.util.List<com.nezhahq.agent.proto.State_SensorTemperature.Builder> 
         getTemperaturesBuilderList() {
      return getTemperaturesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nezhahq.agent.proto.State_SensorTemperature, com.nezhahq.agent.proto.State_SensorTemperature.Builder, com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder> 
        getTemperaturesFieldBuilder() {
      if (temperaturesBuilder_ == null) {
        temperaturesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nezhahq.agent.proto.State_SensorTemperature, com.nezhahq.agent.proto.State_SensorTemperature.Builder, com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder>(
                temperatures_,
                ((bitField0_ & 0x00008000) != 0),
                getParentForChildren(),
                isClean());
        temperatures_ = null;
      }
      return temperaturesBuilder_;
    }

    private com.google.protobuf.Internal.DoubleList gpu_ = emptyDoubleList();
    private void ensureGpuIsMutable() {
      if (!gpu_.isModifiable()) {
        gpu_ = makeMutableCopy(gpu_);
      }
      bitField0_ |= 0x00010000;
    }
    private void ensureGpuIsMutable(int capacity) {
      if (!gpu_.isModifiable()) {
        gpu_ = makeMutableCopy(gpu_, capacity);
      }
      bitField0_ |= 0x00010000;
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @return A list containing the gpu.
     */
    public java.util.List<java.lang.Double>
        getGpuList() {
      gpu_.makeImmutable();
      return gpu_;
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @return The count of gpu.
     */
    public int getGpuCount() {
      return gpu_.size();
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @param index The index of the element to return.
     * @return The gpu at the given index.
     */
    public double getGpu(int index) {
      return gpu_.getDouble(index);
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @param index The index to set the value at.
     * @param value The gpu to set.
     * @return This builder for chaining.
     */
    public Builder setGpu(
        int index, double value) {

      ensureGpuIsMutable();
      gpu_.setDouble(index, value);
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @param value The gpu to add.
     * @return This builder for chaining.
     */
    public Builder addGpu(double value) {

      ensureGpuIsMutable();
      gpu_.addDouble(value);
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @param values The gpu to add.
     * @return This builder for chaining.
     */
    public Builder addAllGpu(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureGpuIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, gpu_);
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double gpu = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearGpu() {
      gpu_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00010000);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.State)
  }

  // @@protoc_insertion_point(class_scope:proto.State)
  private static final com.nezhahq.agent.proto.State DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nezhahq.agent.proto.State();
  }

  public static com.nezhahq.agent.proto.State getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<State>
      PARSER = new com.google.protobuf.AbstractParser<State>() {
    @java.lang.Override
    public State parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<State> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<State> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nezhahq.agent.proto.State getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

