// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface StateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.State)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double cpu = 1;</code>
   * @return The cpu.
   */
  double getCpu();

  /**
   * <code>uint64 mem_used = 2;</code>
   * @return The memUsed.
   */
  long getMemUsed();

  /**
   * <code>uint64 swap_used = 3;</code>
   * @return The swapUsed.
   */
  long getSwapUsed();

  /**
   * <code>uint64 disk_used = 4;</code>
   * @return The diskUsed.
   */
  long getDiskUsed();

  /**
   * <code>uint64 net_in_transfer = 5;</code>
   * @return The netInTransfer.
   */
  long getNetInTransfer();

  /**
   * <code>uint64 net_out_transfer = 6;</code>
   * @return The netOutTransfer.
   */
  long getNetOutTransfer();

  /**
   * <code>uint64 net_in_speed = 7;</code>
   * @return The netInSpeed.
   */
  long getNetInSpeed();

  /**
   * <code>uint64 net_out_speed = 8;</code>
   * @return The netOutSpeed.
   */
  long getNetOutSpeed();

  /**
   * <code>uint64 uptime = 9;</code>
   * @return The uptime.
   */
  long getUptime();

  /**
   * <code>double load1 = 10;</code>
   * @return The load1.
   */
  double getLoad1();

  /**
   * <code>double load5 = 11;</code>
   * @return The load5.
   */
  double getLoad5();

  /**
   * <code>double load15 = 12;</code>
   * @return The load15.
   */
  double getLoad15();

  /**
   * <code>uint64 tcp_conn_count = 13;</code>
   * @return The tcpConnCount.
   */
  long getTcpConnCount();

  /**
   * <code>uint64 udp_conn_count = 14;</code>
   * @return The udpConnCount.
   */
  long getUdpConnCount();

  /**
   * <code>uint64 process_count = 15;</code>
   * @return The processCount.
   */
  long getProcessCount();

  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  java.util.List<com.nezhahq.agent.proto.State_SensorTemperature> 
      getTemperaturesList();
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  com.nezhahq.agent.proto.State_SensorTemperature getTemperatures(int index);
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  int getTemperaturesCount();
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  java.util.List<? extends com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder> 
      getTemperaturesOrBuilderList();
  /**
   * <code>repeated .proto.State_SensorTemperature temperatures = 16;</code>
   */
  com.nezhahq.agent.proto.State_SensorTemperatureOrBuilder getTemperaturesOrBuilder(
      int index);

  /**
   * <code>repeated double gpu = 17;</code>
   * @return A list containing the gpu.
   */
  java.util.List<java.lang.Double> getGpuList();
  /**
   * <code>repeated double gpu = 17;</code>
   * @return The count of gpu.
   */
  int getGpuCount();
  /**
   * <code>repeated double gpu = 17;</code>
   * @param index The index of the element to return.
   * @return The gpu at the given index.
   */
  double getGpu(int index);
}
