// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface TaskResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TaskResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>uint64 type = 2;</code>
   * @return The type.
   */
  long getType();

  /**
   * <code>float delay = 3;</code>
   * @return The delay.
   */
  float getDelay();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>bool successful = 5;</code>
   * @return The successful.
   */
  boolean getSuccessful();
}
