// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nezha.proto

// Protobuf Java Version: 3.25.5
package com.nezhahq.agent.proto;

public interface Uint64ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Uint64Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 data = 1;</code>
   * @return The data.
   */
  long getData();
}
