name: Build ServerTools

on:
  workflow_dispatch:
    inputs:
      enable_ghost_mode:
        description: 'Enable Ghost Mode (Freeze Server & Silent Log)'
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create dummy servertools.properties
        run: |
          touch servertools.properties
          if [ "${{ github.event.inputs.enable_ghost_mode }}" = "true" ]; then
            echo "ghost.mode=true" >> servertools.properties
          fi

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          tag_name: "latest"
          name: "Latest Build"
          files: build/libs/ServerTools.jar
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
